### ISSUE TITLE
Precompiled regex

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#14]
I noticed that the regex examples pass the string pattern on each test, unlike all languages I'm familiar with where regexes are first-class objects that you construct (hence only get compiled once) and can pass around...

There's not any kind of internal cache of compiled regexes is there?

If not I might feel tempted to make a `Regex` Ć class in userland with a bunch of conditional compilation and extern blocks for each target language.

**Comment by pfusik** [comment]
That's high on my todo list. The only thing that stops me is that I'd like to implement it as method overloads and Ć doesn't support that. That's not a big problem for built-in methods, I just need to figure out how to do it best. The API will be like:

```csharp
Regex# re = Regex.Compile("ABC-\\d+", RegexOptions.IgnoreCase); // options are optional, not sure about the shared pointer yet
re.IsMatch(str); // instance overload to the existing static method
Match() m;
m.Find(str, re); // overload
```

C++, C#, Java, JavaScript, Python all support regex objects. BTW. only last days did I discover that C++ has `<regex>` !

**Comment by jedwards1211** [comment]
I see, sounds good! For what it's worth, if I had to do it without overloads I would use the builder pattern:

```
Regex# foo = new RegexBuilder("[a-z0-9]").IgnoreCase().Compile()
```

**Comment by pfusik** [comment]
It's the `IsMatch` and `Find` methods that are overloaded. I don't see how the builder pattern would help here -- perhaps you missed that Ć has default argument values?

Anyway, it's already implemented and I've just pushed the doc update.

Would you need to continue the search in the same string? JS allows this in a strange way: the regex must have the "global" flag and the position is held in the regex object (instead of the match). This doesn't fit too well... Also, JS is the only language that doesn't let you specify the starting position for the search.
