### ISSUE TITLE
Is uninitialized string storage supposed to be allowed?

### ISSUE THREAD

**Issue by jedwards1211** [pfusik/cito#41]
```csharp
public class Test
{
	public static bool Run()
	{
		string() foo;
		string() bar;
		return foo.StartsWith(bar);
	}
}
```

Cito compiles this successfully.  In C++ it passes since a `std::string` declaration is the empty string, but in other languages the variables are null or undefined, and the test fails:

- C: segfault
- C++: passes
- Java: compile error
- JavaScript: crashes with `TypeError`
- Python: crashes with `NameError`
- Swift: compile error

**Comment by pfusik** [comment]
This is invalid code.

String storage isn't any special, except in C++ it's much easier to have `std::string` initialized than not.

`cito` doesn't currently check for usage of uninitialized variables. While in this particular example it looks obvious, in the general case it's not. Consider:

    if (i > 4)
        foo = "foo";
    while (AnotherCondition() || i > 0) {
        bar = "bar";
        if (Quux())
            break;
    }
    if (i == 10 && Quux())
        return foo.StartsWith(bar); // both initialized!

Since most of the target compilers signal the error (also the C compiler with warnings), I consider this issue low-priority.

**Comment by pfusik** [comment]
I added warnings in the documentation.
