### ISSUE TITLE
What about semantc version in repo tags?

### ISSUE THREAD

**Issue by ShamanR** [pfusik/cito#47]
What about semantc version in repo tags?

Is it 1.0.0 or 0.0.1 ?
Can you call stable?

**Comment by pfusik** [comment]
Good question!

There are no Git tags here.
cito was originally hosted on SourceForge and released up to 0.4.0.
Since then, it underwent a complete rewrite, which is the only reason `cito --version` prints 1.0.0.

The first commit was in 2011, so it's certainly not 0.0.1.
Language design is mature, I don't expect major breaking changes.
On the other hand, as you can see, there are open bugs and features, so it's not bullet-proof.
This is a developer's tool and I expect the interested developers to update and build themselves.

**Comment by pfusik** [comment]
Released 2.0.0 with:
- `cito` binary released as a .NET tool
- a syntax highlighting extension for Visual Studio Code released in its Marketplace

See https://github.com/pfusik/cito/blob/master/doc/getting-started.md
I plan to tag the versions from now on.
